export const payments = [
  {
    id: "TXN-123456",
    memberName: "John Doe",
    memberEmail: "john.doe@example.com",
    plan: "Premium",
    amount: 59.0,
    date: "2023-04-01T10:30:00",
    status: "successful",
    paymentMethod: "Credit Card",
    cardLast4: "4242",
  },
  {
    id: "TXN-123457",
    memberName: "Jane Smith",
    memberEmail: "jane.smith@example.com",
    plan: "Basic",
    amount: 29.0,
    date: "2023-04-02T14:15:00",
    status: "successful",
    paymentMethod: "PayPal",
  },
  {
    id: "TXN-123458",
    memberName: "Michael Johnson",
    memberEmail: "michael.johnson@example.com",
    plan: "Elite",
    amount: 99.0,
    date: "2023-04-03T09:45:00",
    status: "failed",
    paymentMethod: "Credit Card",
    cardLast4: "1234",
    failureReason: "Insufficient funds",
  },
  {
    id: "TXN-123459",
    memberName: "Emily Davis",
    memberEmail: "emily.davis@example.com",
    plan: "Premium",
    amount: 59.0,
    date: "2023-04-05T16:20:00",
    status: "successful",
    paymentMethod: "Credit Card",
    cardLast4: "5678",
  },
  {
    id: "TXN-123460",
    memberName: "Robert Wilson",
    memberEmail: "robert.wilson@example.com",
    plan: "Basic",
    amount: 29.0,
    date: "2023-04-07T11:10:00",
    status: "pending",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "TXN-123461",
    memberName: "Sarah Brown",
    memberEmail: "sarah.brown@example.com",
    plan: "Elite",
    amount: 99.0,
    date: "2023-04-10T13:30:00",
    status: "successful",
    paymentMethod: "Credit Card",
    cardLast4: "9012",
  },
  {
    id: "TXN-123462",
    memberName: "David Miller",
    memberEmail: "david.miller@example.com",
    plan: "Premium",
    amount: 59.0,
    date: "2023-04-12T08:45:00",
    status: "successful",
    paymentMethod: "PayPal",
  },
  {
    id: "TXN-123463",
    memberName: "Jennifer Taylor",
    memberEmail: "jennifer.taylor@example.com",
    plan: "Basic",
    amount: 29.0,
    date: "2023-04-15T15:20:00",
    status: "refunded",
    paymentMethod: "Credit Card",
    cardLast4: "3456",
    refundReason: "Customer request",
  },
  {
    id: "TXN-123464",
    memberName: "James Anderson",
    memberEmail: "james.anderson@example.com",
    plan: "Elite",
    amount: 99.0,
    date: "2023-04-18T10:15:00",
    status: "failed",
    paymentMethod: "Credit Card",
    cardLast4: "7890",
    failureReason: "Expired card",
  },
  {
    id: "TXN-123465",
    memberName: "Lisa Thomas",
    memberEmail: "lisa.thomas@example.com",
    plan: "Premium",
    amount: 59.0,
    date: "2023-04-20T14:30:00",
    status: "successful",
    paymentMethod: "Credit Card",
    cardLast4: "2345",
  },
  {
    id: "TXN-123466",
    memberName: "Daniel Jackson",
    memberEmail: "daniel.jackson@example.com",
    plan: "Basic",
    amount: 29.0,
    date: "2023-04-22T09:10:00",
    status: "successful",
    paymentMethod: "PayPal",
  },
  {
    id: "TXN-123467",
    memberName: "Michelle White",
    memberEmail: "michelle.white@example.com",
    plan: "Elite",
    amount: 99.0,
    date: "2023-04-25T16:45:00",
    status: "successful",
    paymentMethod: "Credit Card",
    cardLast4: "6789",
  },
  {
    id: "TXN-123468",
    memberName: "Christopher Harris",
    memberEmail: "christopher.harris@example.com",
    plan: "Premium",
    amount: 59.0,
    date: "2023-04-28T11:30:00",
    status: "pending",
    paymentMethod: "Bank Transfer",
  },
  {
    id: "TXN-123469",
    memberName: "Amanda Martin",
    memberEmail: "amanda.martin@example.com",
    plan: "Basic",
    amount: 29.0,
    date: "2023-04-30T13:15:00",
    status: "successful",
    paymentMethod: "Credit Card",
    cardLast4: "0123",
  },
]
