export const staff = [
  {
    id: "staff1",
    name: "Alex Johnson",
    email: "alex.johnson@fitzone.com",
    role: "trainer",
    joinDate: "2021-05-15",
    status: "active",
    specialization: "Strength Training",
  },
  {
    id: "staff2",
    name: "Samantha Lee",
    email: "samantha.lee@fitzone.com",
    role: "trainer",
    joinDate: "2021-08-20",
    status: "active",
    specialization: "Yoga",
  },
  {
    id: "staff3",
    name: "Marcus Williams",
    email: "marcus.williams@fitzone.com",
    role: "trainer",
    joinDate: "2022-01-10",
    status: "active",
    specialization: "Cardio",
  },
  {
    id: "staff4",
    name: "Jessica Chen",
    email: "jessica.chen@fitzone.com",
    role: "trainer",
    joinDate: "2022-03-05",
    status: "active",
    specialization: "Pilates",
  },
  {
    id: "staff5",
    name: "David Miller",
    email: "david.miller@fitzone.com",
    role: "admin",
    joinDate: "2020-11-15",
    status: "active",
  },
  {
    id: "staff6",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@fitzone.com",
    role: "staff",
    joinDate: "2022-05-20",
    status: "active",
    department: "Front Desk",
  },
  {
    id: "staff7",
    name: "Michael Brown",
    email: "michael.brown@fitzone.com",
    role: "staff",
    joinDate: "2022-06-10",
    status: "active",
    department: "Maintenance",
  },
  {
    id: "staff8",
    name: "Sarah Wilson",
    email: "sarah.wilson@fitzone.com",
    role: "trainer",
    joinDate: "2022-08-15",
    status: "inactive",
    specialization: "CrossFit",
  },
  {
    id: "staff9",
    name: "Robert Taylor",
    email: "robert.taylor@fitzone.com",
    role: "admin",
    joinDate: "2021-02-20",
    status: "active",
  },
  {
    id: "staff10",
    name: "Jennifer Adams",
    email: "jennifer.adams@fitzone.com",
    role: "staff",
    joinDate: "2022-09-05",
    status: "active",
    department: "Membership Services",
  },
]
